### ISSUE TITLE
error in inference

### ISSUE THREAD

**Issue by z411500976** [JosonChan1998/KE-RCNN#1]
hi,i got an error
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 ./tools/dist_test.sh configs/ke_rcnn/ke_rcnn_r50_fpn_fashion_1x.py work_dirs/ke_rcnn_r50_fpn_fashion_1x/epoch32.pth 8 --format-only --eval-options "jsonfile_prefix=work_dirs/ke_rcnn_r50_fpn_fashion_1x/ke_rcnn_r50_fpn_fashion_1x_val_result"`

![20221125171903](https://user-images.githubusercontent.com/24216715/203945132-258ac8e6-b939-45a2-8bbf-6343beffc598.png)

**Comment by JosonChan1998** [comment]
Thanks for pointing out this error.
It seems that the attr matrix link is wrong. I have fixed it. Please try again.
